stages:
  - name: package
    steps:
      - runScriptConfig:
          image: node:10.23.1
          shellScript: |-
            npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass
            npm install --registry http://nexus.tongtech.top:9090/repository/npm-public/
            DISABLE_ESLINT=1
            npm run build
  - name: release
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: cnfic-usermanage/cnfic-usermanage-ui:v1.${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: docker-hosted.tongtech.top
  - name: depoly
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
timeout: 60
branch:
  include:
    - dev
notification: { }
